- name: update
  apt: 
    update_cache: yes
    upgrade: yes
  tags:
  - update apt

- name: NGINX | Install NGINX
  apt:
    name: nginx
    state: latest
  notify:
  - restart nginx
  tags:
  - nginx-package

- name: copy nginx.conf
  copy:
    src: files/web/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart nginx
